CREATE TABLE IF NOT EXISTS market_quant_features (
  metal_code text NOT NULL,
  metal_name text NOT NULL,
  price_date date NOT NULL,
  close_price numeric(18,6) NOT NULL,
  source_provider text,
  source_type text,
  return_1d double precision,
  return_3d double precision,
  return_7d double precision,
  return_14d double precision,
  return_30d double precision,
  return_60d double precision,
  return_90d double precision,
  rolling_mean_7d double precision,
  rolling_mean_14d double precision,
  rolling_mean_30d double precision,
  rolling_mean_60d double precision,
  rolling_mean_90d double precision,
  rolling_std_7d double precision,
  rolling_std_14d double precision,
  rolling_std_30d double precision,
  rolling_std_60d double precision,
  rolling_std_90d double precision,
  momentum_7d double precision,
  momentum_30d double precision,
  momentum_90d double precision,
  zscore_30d double precision,
  zscore_90d double precision,
  drawdown_30d double precision,
  drawdown_90d double precision,
  pct_rank_30d double precision,
  pct_rank_90d double precision,
  industrial_avg_return_7d double precision,
  industrial_avg_return_30d double precision,
  industrial_avg_return_90d double precision,
  relative_strength_7d double precision,
  relative_strength_30d double precision,
  relative_strength_90d double precision,
  target_return_7d double precision,
  target_return_30d double precision,
  target_return_90d double precision,
  target_direction_7d integer,
  target_direction_30d integer,
  target_direction_90d integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_quant_features_pkey PRIMARY KEY (metal_code, price_date)
);

CREATE TABLE IF NOT EXISTS market_pair_features (
  price_date date NOT NULL,
  base_metal_code text NOT NULL,
  compare_metal_code text NOT NULL,
  base_price numeric(18,6) NOT NULL,
  compare_price numeric(18,6) NOT NULL,
  price_ratio double precision,
  spread_return_7d double precision,
  spread_return_30d double precision,
  spread_return_90d double precision,
  target_pair_return_7d double precision,
  target_pair_return_30d double precision,
  target_pair_return_90d double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_pair_features_pkey PRIMARY KEY (price_date, base_metal_code, compare_metal_code)
);

CREATE TABLE IF NOT EXISTS market_model_versions (
  model_name text NOT NULL,
  model_version text NOT NULL,
  model_type text NOT NULL,
  horizon_day integer NOT NULL,
  train_start_date date,
  train_end_date date,
  feature_count integer,
  sample_count integer,
  metal_count integer,
  model_path text,
  feature_config_path text,
  train_status text NOT NULL,
  mae_return double precision,
  direction_accuracy double precision,
  rank_ic_mean double precision,
  rank_ic_std double precision,
  rank_ic_sharpe double precision,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_model_versions_pkey PRIMARY KEY (model_name, model_version, horizon_day)
);

CREATE TABLE IF NOT EXISTS market_quant_forecasts (
  model_version text NOT NULL,
  forecast_date date NOT NULL,
  metal_code text NOT NULL,
  metal_name text NOT NULL,
  base_price numeric(18,6) NOT NULL,
  horizon_day integer NOT NULL,
  predicted_return double precision NOT NULL,
  predicted_price numeric(18,6) NOT NULL,
  predicted_direction integer NOT NULL,
  direction_confidence double precision,
  volatility_level text,
  relative_strength_score double precision,
  relative_strength_rank integer,
  risk_level text,
  procurement_signal text,
  procurement_advice text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT market_quant_forecasts_pkey PRIMARY KEY (model_version, forecast_date, metal_code, horizon_day)
);

CREATE INDEX IF NOT EXISTS idx_market_quant_features_date ON market_quant_features(price_date DESC);
CREATE INDEX IF NOT EXISTS idx_market_pair_features_date ON market_pair_features(price_date DESC);
CREATE INDEX IF NOT EXISTS idx_market_quant_forecasts_date ON market_quant_forecasts(forecast_date DESC, horizon_day);
