import type { MetalRanking, DetailResponse } from "./market-utils";

const today = new Date();
function d(offset: number): string {
  const dt = new Date(today);
  dt.setDate(dt.getDate() + offset);
  return dt.toISOString().slice(0, 10);
}

export const MOCK_RANKING: MetalRanking[] = [
  { metal_code: "CU", metal_name: "铜", base_price: 82500, final_predicted_return: 0.032, final_predicted_price: 85140, relative_strength_rank: 1, procurement_signal: "建议采购" },
  { metal_code: "AL", metal_name: "铝", base_price: 20800, final_predicted_return: -0.015, final_predicted_price: 20488, relative_strength_rank: 3, procurement_signal: "观望" },
  { metal_code: "NI", metal_name: "镍", base_price: 128500, final_predicted_return: 0.018, final_predicted_price: 130813, relative_strength_rank: 2, procurement_signal: "适量采购" },
  { metal_code: "ZN", metal_name: "锌", base_price: 23200, final_predicted_return: -0.022, final_predicted_price: 22690, relative_strength_rank: 5, procurement_signal: "延迟采购" },
  { metal_code: "SN", metal_name: "锡", base_price: 268000, final_predicted_return: 0.005, final_predicted_price: 269340, relative_strength_rank: 4, procurement_signal: "观望" },
  { metal_code: "PB", metal_name: "铅", base_price: 16800, final_predicted_return: -0.008, final_predicted_price: 16666, relative_strength_rank: 6, procurement_signal: "延迟采购" },
];

function stableNoise(seed: number): number {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
}

function makeHistory(basePrice: number, days: number = 90) {
  const result: { date: string; actual_price: number }[] = [];
  let price = basePrice * 0.96;
  for (let i = days; i >= 0; i--) {
    price += (stableNoise(basePrice + i * 17) - 0.48) * basePrice * 0.005;
    price = Math.max(basePrice * 0.85, Math.min(basePrice * 1.15, price));
    result.push({ date: d(-i), actual_price: Math.round(price) });
  }
  return result;
}

function makeForecast(basePrice: number, forecastDate: string) {
  return [
    {
      forecast_date: forecastDate,
      horizon_day: 7,
      metal_code: "CU",
      metal_name: "铜",
      base_price: basePrice,
      final_predicted_return: 0.012,
      final_predicted_price: Math.round(basePrice * 1.012),
      predicted_return_p10: -0.005,
      predicted_return_p50: 0.012,
      predicted_return_p90: 0.028,
      predicted_price_p10: Math.round(basePrice * 0.995),
      predicted_price_p50: Math.round(basePrice * 1.012),
      predicted_price_p90: Math.round(basePrice * 1.028),
      relative_strength_rank: 1,
      volatility_level: "中",
      risk_level: "低",
      procurement_signal: "建议采购",
      procurement_advice: "短期价格上行概率较高",
      key_drivers: { base_lgb: 0.015, market_factor: 0.008, catboost_excess: -0.003, pair_adjustment: -0.008 },
      data_quality_score: 0.92,
      model_reliability_level: "高",
      forecast_target_date: d(7),
      reliability_score: 82,
      reliability_score_note: "较稳定",
      interval_judgement: "方向一致向上",
      interval_width: 0.033,
      reliability_score_breakdown: { data_quality: 32, direction_interval: 30, interval_width: 19, median_signal: 7 },
      reliability_score_reasons: ["数据质量贡献 32/35", "方向区间贡献 30/30：方向一致向上", "区间宽度贡献 19/25", "中位信号贡献 7/10"],
    },
    {
      forecast_date: forecastDate,
      horizon_day: 30,
      metal_code: "CU",
      metal_name: "铜",
      base_price: basePrice,
      final_predicted_return: 0.032,
      final_predicted_price: Math.round(basePrice * 1.032),
      predicted_return_p10: -0.008,
      predicted_return_p50: 0.032,
      predicted_return_p90: 0.065,
      predicted_price_p10: Math.round(basePrice * 0.992),
      predicted_price_p50: Math.round(basePrice * 1.032),
      predicted_price_p90: Math.round(basePrice * 1.065),
      relative_strength_rank: 1,
      volatility_level: "中",
      risk_level: "中",
      procurement_signal: "建议采购",
      procurement_advice: "30天内价格上行概率较高，建议锁定部分采购",
      key_drivers: { base_lgb: 0.025, market_factor: 0.012, catboost_excess: -0.005, pair_adjustment: 0 },
      data_quality_score: 0.88,
      model_reliability_level: "中",
      forecast_target_date: d(30),
      reliability_score: 75,
      reliability_score_note: "较稳定",
      interval_judgement: "区间跨零",
      interval_width: 0.073,
      reliability_score_breakdown: { data_quality: 31, direction_interval: 10, interval_width: 13, median_signal: 10 },
      reliability_score_reasons: ["数据质量贡献 31/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 13/25", "中位信号贡献 10/10"],
    },
    {
      forecast_date: forecastDate,
      horizon_day: 60,
      metal_code: "CU",
      metal_name: "铜",
      base_price: basePrice,
      final_predicted_return: 0.048,
      final_predicted_price: Math.round(basePrice * 1.048),
      predicted_return_p10: -0.022,
      predicted_return_p50: 0.048,
      predicted_return_p90: 0.108,
      predicted_price_p10: Math.round(basePrice * 0.978),
      predicted_price_p50: Math.round(basePrice * 1.048),
      predicted_price_p90: Math.round(basePrice * 1.108),
      relative_strength_rank: 1,
      volatility_level: "高",
      risk_level: "中",
      procurement_signal: "适量采购",
      procurement_advice: "中长期趋势向上但波动加大",
      key_drivers: { base_lgb: 0.035, market_factor: 0.018, catboost_excess: -0.008, pair_adjustment: 0.003 },
      data_quality_score: 0.82,
      model_reliability_level: "中",
      forecast_target_date: d(60),
      reliability_score: 62,
      reliability_score_note: "可参考",
      interval_judgement: "区间跨零",
      interval_width: 0.13,
      reliability_score_breakdown: { data_quality: 29, direction_interval: 10, interval_width: 7, median_signal: 10 },
      reliability_score_reasons: ["数据质量贡献 29/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 7/25", "中位信号贡献 10/10"],
    },
    {
      forecast_date: forecastDate,
      horizon_day: 90,
      metal_code: "CU",
      metal_name: "铜",
      base_price: basePrice,
      final_predicted_return: 0.055,
      final_predicted_price: Math.round(basePrice * 1.055),
      predicted_return_p10: -0.038,
      predicted_return_p50: 0.055,
      predicted_return_p90: 0.138,
      predicted_price_p10: Math.round(basePrice * 0.962),
      predicted_price_p50: Math.round(basePrice * 1.055),
      predicted_price_p90: Math.round(basePrice * 1.138),
      relative_strength_rank: 2,
      volatility_level: "高",
      risk_level: "高",
      procurement_signal: "谨慎采购",
      procurement_advice: "90天波动区间较大，建议分批采购",
      key_drivers: { base_lgb: 0.042, market_factor: 0.022, catboost_excess: -0.012, pair_adjustment: 0.003 },
      data_quality_score: 0.75,
      model_reliability_level: "低",
      forecast_target_date: d(90),
      reliability_score: 48,
      reliability_score_note: "需谨慎",
      interval_judgement: "区间跨零",
      interval_width: 0.176,
      reliability_score_breakdown: { data_quality: 26, direction_interval: 10, interval_width: 7, median_signal: 10 },
      reliability_score_reasons: ["数据质量贡献 26/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 7/25", "中位信号贡献 10/10"],
    },
  ];
}

const MOCK_DETAIL_MAP: Record<string, (code: string) => DetailResponse> = {
  CU: (code) => ({
    metal_code: code,
    metal_name: "铜",
    forecast_date: d(0),
    base_price: 82500,
    current_signal: {
      final_predicted_return_30d: 0.032,
      final_predicted_price_30d: 85140,
      relative_strength_rank: 1,
      risk_level: "中",
      procurement_signal: "建议采购",
      procurement_advice: "30天内价格上行概率较高，建议锁定部分采购",
      model_reliability_level: "中",
      reliability_score: 75,
      reliability_score_note: "较稳定",
      interval_judgement: "区间跨零",
      interval_width: 0.073,
      reliability_score_breakdown: { data_quality: 31, direction_interval: 10, interval_width: 13, median_signal: 10 },
      reliability_score_reasons: ["数据质量贡献 31/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 13/25", "中位信号贡献 10/10"],
      volatility_level: "中",
    },
    history: makeHistory(82500),
    forecasts: makeForecast(82500, d(0)),
  }),
  AL: (code) => ({
    metal_code: code,
    metal_name: "铝",
    forecast_date: d(0),
    base_price: 20800,
    current_signal: {
      final_predicted_return_30d: -0.015,
      final_predicted_price_30d: 20488,
      relative_strength_rank: 3,
      risk_level: "低",
      procurement_signal: "观望",
      procurement_advice: "短期价格偏弱，建议观望",
      model_reliability_level: "高",
      reliability_score: 82,
      reliability_score_note: "较稳定",
      interval_judgement: "方向一致向下",
      interval_width: 0.028,
      reliability_score_breakdown: { data_quality: 30, direction_interval: 30, interval_width: 25, median_signal: 4 },
      reliability_score_reasons: ["数据质量贡献 30/35", "方向区间贡献 30/30：方向一致向下", "区间宽度贡献 25/25", "中位信号贡献 4/10"],
      volatility_level: "低",
    },
    history: makeHistory(20800),
    forecasts: makeForecast(20800, d(0)).map((f) => ({
      ...f,
      metal_code: code,
      metal_name: "铝",
      base_price: 20800,
    })),
  }),
  NI: (code) => ({
    metal_code: code,
    metal_name: "镍",
    forecast_date: d(0),
    base_price: 128500,
    current_signal: {
      final_predicted_return_30d: 0.018,
      final_predicted_price_30d: 130813,
      relative_strength_rank: 2,
      risk_level: "中",
      procurement_signal: "适量采购",
      procurement_advice: "镍价温和上行，适量采购",
      model_reliability_level: "中",
      reliability_score: 68,
      reliability_score_note: "较稳定",
      interval_judgement: "区间跨零",
      interval_width: 0.055,
      reliability_score_breakdown: { data_quality: 28, direction_interval: 10, interval_width: 19, median_signal: 7 },
      reliability_score_reasons: ["数据质量贡献 28/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 19/25", "中位信号贡献 7/10"],
      volatility_level: "中",
    },
    history: makeHistory(128500),
    forecasts: makeForecast(128500, d(0)).map((f) => ({
      ...f,
      metal_code: code,
      metal_name: "镍",
      base_price: 128500,
    })),
  }),
  ZN: (code) => ({
    metal_code: code,
    metal_name: "锌",
    forecast_date: d(0),
    base_price: 23200,
    current_signal: {
      final_predicted_return_30d: -0.022,
      final_predicted_price_30d: 22690,
      relative_strength_rank: 5,
      risk_level: "中",
      procurement_signal: "延迟采购",
      procurement_advice: "锌价预计下行，建议延迟",
      model_reliability_level: "中",
      reliability_score: 55,
      reliability_score_note: "可参考",
      interval_judgement: "方向不明确",
      interval_width: 0.095,
      reliability_score_breakdown: { data_quality: 26, direction_interval: 16, interval_width: 13, median_signal: 4 },
      reliability_score_reasons: ["数据质量贡献 26/35", "方向区间贡献 16/30：方向不明确", "区间宽度贡献 13/25", "中位信号贡献 4/10"],
      volatility_level: "高",
    },
    history: makeHistory(23200),
    forecasts: makeForecast(23200, d(0)).map((f) => ({
      ...f,
      metal_code: code,
      metal_name: "锌",
      base_price: 23200,
    })),
  }),
  SN: (code) => ({
    metal_code: code,
    metal_name: "锡",
    forecast_date: d(0),
    base_price: 268000,
    current_signal: {
      final_predicted_return_30d: 0.005,
      final_predicted_price_30d: 269340,
      relative_strength_rank: 4,
      risk_level: "低",
      procurement_signal: "观望",
      procurement_advice: "锡价走势平稳",
      model_reliability_level: "高",
      reliability_score: 78,
      reliability_score_note: "较稳定",
      interval_judgement: "区间跨零",
      interval_width: 0.042,
      reliability_score_breakdown: { data_quality: 32, direction_interval: 10, interval_width: 19, median_signal: 4 },
      reliability_score_reasons: ["数据质量贡献 32/35", "方向区间贡献 10/30：区间跨零", "区间宽度贡献 19/25", "中位信号贡献 4/10"],
      volatility_level: "低",
    },
    history: makeHistory(268000),
    forecasts: makeForecast(268000, d(0)).map((f) => ({
      ...f,
      metal_code: code,
      metal_name: "锡",
      base_price: 268000,
    })),
  }),
  PB: (code) => ({
    metal_code: code,
    metal_name: "铅",
    forecast_date: d(0),
    base_price: 16800,
    current_signal: {
      final_predicted_return_30d: -0.008,
      final_predicted_price_30d: 16666,
      relative_strength_rank: 6,
      risk_level: "低",
      procurement_signal: "延迟采购",
      procurement_advice: "铅价小幅下行",
      model_reliability_level: "中",
      reliability_score: 60,
      reliability_score_note: "可参考",
      interval_judgement: "方向不明确",
      interval_width: 0.065,
      reliability_score_breakdown: { data_quality: 25, direction_interval: 16, interval_width: 19, median_signal: 1 },
      reliability_score_reasons: ["数据质量贡献 25/35", "方向区间贡献 16/30：方向不明确", "区间宽度贡献 19/25", "中位信号贡献 1/10"],
      volatility_level: "中",
    },
    history: makeHistory(16800),
    forecasts: makeForecast(16800, d(0)).map((f) => ({
      ...f,
      metal_code: code,
      metal_name: "铅",
      base_price: 16800,
    })),
  }),
};

export function getMockDetail(metalCode: string): DetailResponse {
  const factory = MOCK_DETAIL_MAP[metalCode];
  if (factory) return factory(metalCode);
  return MOCK_DETAIL_MAP["CU"]("CU");
}
